In [7]:
import numpy as np
from scipy.stats import binned_statistic

data = np.random.rand(100)
bin_means = binned_statistic(data, data, bins=50, range=(0, 1))[0]

In [8]:
bin_means

array([0.00226888, 0.02556046, 0.05249916, 0.06615998, 0.09657614,
       0.11053436, 0.13615797, 0.14048912, 0.16518654, 0.18969645,
       0.21661536, 0.23074954,        nan,        nan, 0.29529402,
              nan,        nan, 0.34779207, 0.37585559, 0.38546844,
       0.40866914, 0.42866417, 0.44539375,        nan, 0.49181095,
       0.50753877, 0.53487174,        nan, 0.56604805,        nan,
       0.60879742,        nan, 0.64889839, 0.6662205 ,        nan,
              nan, 0.72681254, 0.75684913, 0.77321844, 0.79006653,
       0.8062669 , 0.82915585, 0.85147433,        nan, 0.89341843,
       0.90783459, 0.93500978, 0.94789185, 0.96928652, 0.99984234])

In [9]:
np.histogram(np.random.rand(100), np.arange(0, 100, 10))

(array([100,   0,   0,   0,   0,   0,   0,   0,   0]),
 array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [10]:
np.random.rand(100)

array([0.94855623, 0.88342014, 0.31841258, 0.7080758 , 0.56225204,
       0.0140544 , 0.58754835, 0.20285781, 0.55667552, 0.34082422,
       0.9288472 , 0.77781181, 0.5519908 , 0.54385804, 0.57336053,
       0.95294125, 0.28027562, 0.63021738, 0.01236056, 0.87479139,
       0.96068674, 0.21684439, 0.5084723 , 0.17916598, 0.58039094,
       0.34878682, 0.04470062, 0.03725658, 0.84272163, 0.21575043,
       0.09827758, 0.76503696, 0.63812249, 0.23333294, 0.4003827 ,
       0.70333636, 0.43444005, 0.78369627, 0.13761779, 0.94724306,
       0.63596844, 0.49879504, 0.04043737, 0.86076593, 0.96904825,
       0.8975702 , 0.34607073, 0.49060706, 0.16239546, 0.1883221 ,
       0.40743985, 0.01069929, 0.7519687 , 0.83336404, 0.2555921 ,
       0.82381152, 0.07418331, 0.29516107, 0.66494175, 0.03847676,
       0.67687797, 0.91997971, 0.13171019, 0.52628433, 0.67174489,
       0.63242942, 0.90421534, 0.84476899, 0.60751324, 0.79091784,
       0.27246107, 0.94615055, 0.93326843, 0.59022438, 0.11898

In [11]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [12]:
import numpy
data = numpy.random.rand(100)
bins = numpy.linspace(0, 1, 10)
digitized = numpy.digitize(data, bins)
bin_means1 = [data[digitized == i].mean() for i in range(1, len(bins))]

In [13]:
bin_means1

[0.05624290211337007,
 0.16759015353504922,
 0.28748130240202613,
 0.3886815126497651,
 0.5099255537993517,
 0.6119879341473667,
 0.7294373037363147,
 0.8203897354212705,
 0.9503194676141303]

In [10]:
import numpy as np
from scipy.stats import binned_statistic

data = np.random.rand(100)
bin_means = binned_statistic(data, data, bins=10, range=(0, 1))[0]

In [11]:
bin_means

array([0.05113885, 0.15006343, 0.24951037, 0.3459825 , 0.44245771,
       0.56604227, 0.643648  , 0.74783657, 0.83580362, 0.94215446])

In [14]:
import numpy as np

data = np.random.rand(100)
bins = 10
slices = np.linspace(0, 100, bins+1, True).astype(np.int)
counts = np.diff(slices)

mean = np.add.reduceat(data, slices[:-1]) / counts
print mean

[0.50262847 0.41716175 0.50731987 0.59543146 0.507083   0.37819309
 0.4775056  0.5626248  0.49517319 0.60054984]


In [15]:
slices

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [16]:
counts

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [3]:
import numpy as np
bins=10
np.linspace(0, 100, bins+1, True).astype(np.int)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [4]:
np.histogram(np.random.rand(100), np.arange(0, 100, 10))

(array([100,   0,   0,   0,   0,   0,   0,   0,   0]),
 array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [5]:
import numpy as np
bins=10
slice = np.linspace(0, 100, bins+1, True).astype(np.int)
np.histogram(np.random.rand(100), slice)

(array([100,   0,   0,   0,   0,   0,   0,   0,   0,   0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))